services:
  backup-gitlab:
    build:
      context: .
      args:
        - DOCKER_REGISTRY=docker.io
        - DOCKER_IMAGE_TAG=cytopia/ansible:2.13-tools
        - PRIVATE_KEY_PATH=key.pem
    volumes:
      - ./playbooks:/ansible/playbooks
      - ./hosts.yml:/ansible/hosts.yml
      - ./key.pem:/ansible/key.pem
